### ISSUE TITLE
Clicking systray applet icon does nothing

### ISSUE THREAD

**Issue by ralphee** [Antiz96/arch-update#162]
arch-update 2.0.1

when left clicking the icon in the system tray (hyprland / waybar) nothing happend

when right clicking the icon an small white line appears just at the base of the arch logo

(for now i have set up a keybind)

**Comment by Antiz96** [comment]
Hi,

Can you stop the currently running systray applet (either by killing the process or stopping the systemd service if you used that), relaunch a new one by running `arch-update --tray` in a terminal, click it and post the terminal output here please?

**Comment by Antiz96** [comment]
> receive the following message (also note i did not have an icon i just guessed where it would be)
> 

Since you're running Wayland, make sure you have you have [`qt6-wayland` installed](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=arch-update#n16).

> `gio: Unable to launch application ‘/usr/share/applications/arch-update.desktop’: Unable to find terminal required for application`
> 

This is not an issue with Arch-Update specifically but with gio/glib2 that as a [limited list of known/supported terminals](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L2694). You would probably have the same issue trying to launch `htop` for the `htop.desktop` file for instance.

To workaround this, you can either copy the `arch-update.desktop` to `$HOME/.local/share/applications/arch-update.desktop` (see [this](https://github.com/Antiz96/arch-update?tab=readme-ov-file#the-systray-applet) for more details) and modify the `Exec` line in it to "force" arch-update to launch with your terminal (e.g.  `alacritty -e arch-update`) or create a symlink for your terminal that points to `/usr/bin/xterm` (which is the fallback option for `gio`).

**Comment by Antiz96** [comment]
Alternatively, you can obviously install one of the terminal [known/supported by gio/glib2](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L2694) instead.

**Comment by Antiz96** [comment]
While waiting for Gnome to find and implement a way to support any terminal emulators in `gio`, I'm gonna document the workaround somewhere (maybe in the [Tips and Tricks](https://github.com/Antiz96/arch-update?tab=readme-ov-file#tips-and-tricks) section of the README/man page?), as I assume you won't be the only one facing this situation :sweat_smile:

**Comment by erikfrish** [comment]
I solved this issue for me by deleting gnome-terminal and gnome-console, installing xdg-terminal-exec and adding kitty.desktop to ~/.config/xdg-terminals.list, now everything opens in kitty including arch-update
