### ISSUE TITLE
Arch-Update shortcut appears under "Lost & Found" on Plasma desktop

### ISSUE THREAD

**Issue by starscaledragon** [Antiz96/arch-update#178]
I think it happens because the .desktop file needs a `Categories` field,
for example the .desktop file for Plasma System Settings looks like
```
[Desktop Entry]
Exec=systemsettings
Icon=preferences-system
Type=Application
SingleMainWindow=true
X-DocPath=systemsettings/index.html
StartupNotify=true
X-KDE-Shortcuts=Tools
OnlyShowIn=KDE;
Actions=kcm-lookandfeel;kcm-users;kcm-screenlocker;kcm-powerdevilprofilesconfig;kcm-kscreen;
Name=System Settings
X-DBUS-StartupType=Unique
X-DBUS-ServiceName=org.kde.systemsettings
Categories=Qt;KDE;Settings;
...
```

**Comment by Antiz96** [comment]
Hi,

Thanks for the report!

I'm not using Plasma so I'm not sure what "Lost & Found" is referring to in this context?
Is it the application category in the application menu/finder?

**Comment by starscaledragon** [comment]
Yes, it's the application category, it can be seen in the Plasma start menu i.e.
![image](https://github.com/Antiz96/arch-update/assets/174369883/022bc07d-f332-4a93-a633-2fdece1a1849)

**Comment by Antiz96** [comment]
Okay, thanks for the confirmation!

So it's indeed most probably because the .desktop file is missing a category parameter.

The possible values for the main categories are listed [here](https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry).
In my opinion, Arch-Update falls under the "Utility" category.

Can you add the following line into the arch-update.desktop file and check if it moves out of "Lost & Found" please?

```
Categories=Utility
```

(I don't know if Plasma needs to be restarted for the change to apply)

Thanks in advance!

**Comment by starscaledragon** [comment]
Thanks for the quick reply, adding `Categories=Utility` works as intended
![image](https://github.com/Antiz96/arch-update/assets/174369883/9ca6d4f2-d907-4702-a111-22615d45df46)

**Comment by Antiz96** [comment]
Alright! Are you willing to submit a pull request for that?
The .desktop file is under `res/desktop/arch-update.desktop` in the GitHub repo.

If not, I can commit it myself tomorrow. As you prefer :wink:

In any case, thanks once again for the report and the test !

**Comment by starscaledragon** [comment]
If you could commit it yourself tomorrow, that would be great. Thanks again for the support!

**Comment by Antiz96** [comment]
This bug has been fixed in https://github.com/Antiz96/arch-update/pull/179 (thanks @max276 for the PR)
I'll release a new version soon*-ish* :)
