### ISSUE TITLE
Add a DiffProg option in arch-update.conf

### ISSUE THREAD

**Issue by Xdavius** [Antiz96/arch-update#204]
Do you want to treat pacnew files ? -> yes
Select an editor : 

- >  [1] vim (default/terminal)
      [2] meld (GUI)

Something like that.

If you choose 2 -> check if meld is installed, if not -> install

**Comment by Antiz96** [comment]
Hi,

Thanks for the feature request!

I'm not really in favor of adding something **interactive** for that within the script though. Meld isn't the [only option there is](https://wiki.archlinux.org/title/List_of_applications/Utilities#Comparison,_diff,_merge) (and I really don't want to add a choice for *every* option there is :rofl:) and installing packages (in case the selected option is not installed) is totally out of Arch-Update's scope.

However, while I still think most of this is kinda out of Arch-Update's scope overall (since people can just define their default diff program by [exporting the DIFFPROG environment variable](https://wiki.archlinux.org/title/Pacman/Pacnew_and_Pacsave#pacdiff)), I am fine adding a `DiffProg=` option in the `arch-update.conf` file. That would be a good compromise in my opinion, and that would allow people to set up a DIFFPROG specific to Arch-Update (if ever needed).

I'll work on that soon :)
