### ISSUE TITLE
Config for omitting pacnew files

### ISSUE THREAD

**Issue by ubmarco** [Antiz96/arch-update#214]
### Description

I'd like to be able to disable the pacnew feature or maintain a denylist for pacnew files that I never want to handle via arch-update.

### Motivation and context

I see 2 reasons:
- In my daily workflow it's rarely used but needs user interaction.
- Users might mess up their config.

As an example in below output, I see `/etc/passwd` which I certainly want to block from showing up.

### Screenshots / Logs

```text
==> No old or uninstalled cached package found

==> Pacnew Files:
/etc/passwd.pacnew
/etc/shells.pacnew
/etc/locale.gen.pacnew
/etc/lightdm/lightdm-gtk-greeter.conf.pacnew
/etc/mkinitcpio.conf.pacnew
/etc/ssh/sshd_config.pacnew
/etc/pacman.d/mirrorlist.pacnew
/etc/systemd/timesyncd.conf.pacnew
/etc/texmf/web2c/fmtutil.cnf.pacsave

-> Would you like to process these files now? [Y/n]
```

**Comment by Antiz96** [comment]
Hello,

Thanks for the feature request!

To be completely honest, I'm not really sold on this... The idea behind Arch-Update is to guide users into **every** recommended steps for a complete/proper update and dealing with pacnew is certainly one of them (whether it is to apply, merge or remove them; depending on the situation). Indeed, users are actually advised to [deal with them promptly](https://wiki.archlinux.org/title/System_maintenance#Deal_promptly_with_new_configuration_files).

To answer the motivations:

> In my daily workflow it's rarely used but needs user interaction.

I'm not sure to understand if this refers specifically to the pacnew handling part or to Arch-Update as a whole. 
 
For the former, dealing with pacnew indeed requires user interaction as there is no (or not always) a wrong or right answer regarding which action to take. It all comes down to the situation and the user's specific case. Two persons could actually take a different action without any of them choosing **the** right choice (as there's no~~t always~~ such thing). Unfortunately, I'm not sure Arch-Update can do anything about that at its level (and even if it could, I would actually argue this is out of its scope; see the next paragraph).

For the latter, Arch-Update has been specifically designed to run interactively. Indeed, the aim is to guide users through all the recommended steps but not to take any decision for them. Arch Linux expects users to maintain their system themselves, which implies a bunch of [verification and actions](https://wiki.archlinux.org/title/System_maintenance#Upgrading_the_system) to be made before, during and after a system upgrade. Arch-Update is supposed to act as a "wrapper" around all of those checks & actions but do not intend to fully automate them. It is an "helper" more than a "decision maker". So the same way that Arch Linux itself expects it, I would argue that Arch-Update as a whole expects some users intervention/interaction (not only for the pacnew part). Automated (and user interaction free) processes, when it comes to system upgrades, are discouraged and unsupported by Arch Linux (and thus by Arch-Update as well).

> Users might mess up their config.

Well, I can think of numerous scenarios where **not** dealing with pacnew could lead to messed up configs (whether it is to remove a deprecated configuration option from a software's configuration file or a [deprecated repository from pacman's config](https://archlinux.org/news/git-migration-completed/) for instance).

Also, I'm not sure that some people not knowing how to properly deal with pacnews (which indeed can lead to messed up configs) is a good enough reason to hide that step from the upgrade path in Arch-Update. Once again, this is an important and recommended step that people are expected to [deal with promptly](https://wiki.archlinux.org/title/System_maintenance#Deal_promptly_with_new_configuration_files) and they are also expected to know how to do so (or otherwise they can refer to the [dedicated wiki page](https://wiki.archlinux.org/title/Pacman/Pacnew_and_Pacsave)).

> As an example in below output, I see /etc/passwd which I certainly want to block from showing up.

I would advise **not** to do that. You might be able to ignore it for now, but if the the `/bin/bash` symlink to `/usr/bin/bash` is ever removed *(which has little to no chance to happen in a near future to be fair, but that's just an example)*, you will actually **need** to merge/append the diff included in this pacnew (as this is what this specific pacnew [is about](https://gitlab.archlinux.org/archlinux/packaging/packages/filesystem/-/commit/adf12b1575dbb3cbb90a02bdb3b5a00d4d8effd4)), otherwise your user won't point to a valid shell and you won't be able to log in anymore. Again, this probably won't happen anytime soon, this was just to take the example you gave; but the point is that a specific pacnew you can ignore at the moment doesn't mean you'll be able to ignore it forever, so such a "denylist" is dangerous in my opinion. The proper way to deal with that would be to use the `(R)emove pacnew` option for that one during the "processing pacnew" step so it won't show up again (until another pacnew is created for that specific file).

---

Sorry for the long read :sweat_smile: 

To sum up, I know that pacnews tend to bug numerous people that are either not sure how to properly deal with them or not sure which action they should take. But it's still an important and recommend step for a complete/proper update and I personally don't consider this a valid reason to provide an option to hide some (or all) of them. 
In my opinion, if one doesn't want to deal with pacnews, they should just use the `(R)emove pacnew` option during the "pacnew processing" part within Arch-Update. But it has to be an explicit choice of the users themselves. Sometimes, simply removing a pacnew can be the right choice to make, but **blindly** removing/ignoring pacnews is not recommended and I wouldn't support adding an option to just do that at the Arch-Update level itself.

Regardless, I'd like to sincerely thank you for sharing your opinion in this detailed feature request, as well as for your interest in Arch-Update! :pray: 

I'm putting this issue as `wontfix`. Regardless, please feel free to respond to this if you want.
I'm always open for a discussion :smile: 

Otherwise, I can we can just close this issue.

**Comment by Antiz96** [comment]
As this issue did not received any additional comment since then, I'm closing it.
Feel free to add another comment if needed :)
