### ISSUE TITLE
Not of arch-news

### ISSUE THREAD

**Issue by Breizil29** [Antiz96/arch-update#215]
### Environment

- Distribution: Arch Linux
- Windows Manager: Bspwm + Polybar
- Arch-Update version: arch-update 2.3.0

### Description of the bug

Arch-News do not appear during updates

**Comment by Antiz96** [comment]
Hello,

Thanks for the report! 

By default, Arch-Update only shows Arch News during updates if a new one has been published since the last time Arch-Update was executed, so it is normal that the Arch News are not always appearing during updates.

However, if you want the Arch News to appear **everytime** during updates (regardless if there's a new one or not), you can use the `AlwaysShowNews` option in the `arch-update.conf` configuration file:

1 - Run `arch-update --gen-config` to generate an `arch-update.conf` configuration file (if you don't have one already)
2 - Run `arch-update --edit-config` to edit it
3 - Uncomment (or add) the `AlwaysShowNews` option to it.

Alternatively you can run the `arch-update --news` (or `arch-update -n`) command to see the news at any time (outside of updates):

![image](https://github.com/user-attachments/assets/4f17b302-1cda-41dd-92ef-64f326f37c59)

You can optionally specify the number of news to show as an argument (e.g. `arch-update --news 10`) or by using the `NewsNum=[Num]` (e.g. `NewsNum=10`) option in the `arch-update.conf` configuration file.

Does that covers your issue? :)

**Comment by Breizil29** [comment]
Yes thank.
