### ISSUE TITLE
Add option to skip confirmation prompts for package and cache cleanup

### ISSUE THREAD

**Issue by mehanoid** [Antiz96/arch-update#227]
### Description

It would be great to have the ability to configure settings in `arch-update` to allow users to skip certain prompts during the update process. Specifically, the following prompts should have an option to either always perform the action automatically or skip it entirely based on user-defined settings:

- "Would you like to remove these orphan packages (and their potential dependencies) now? [y/N]"
- "Would you like to remove this Flatpak unused package now? [y/N]"
- "Cached Packages: There are old and/or uninstalled cached packages. Would you like to remove them from the cache now? [Y/n]"

To handle these scenarios, you could also consider using pacman’s `--noconfirm` option for package removal.

### Motivation and context

This feature would streamline the update process by eliminating repetitive user input, making the tool more efficient and user-friendly.

**Comment by Antiz96** [comment]
Hello,

Thanks a lot for the feature request!
However, to be honest, I'm not willing to implement such "confirmation skips".

The thing is, the list of orphan packages to remove reported by Arch-Update beforehand might not exactly be equal to what is actually going to be removed by pacman afterwards (as it doesn't include eventual additional dependencies that might be removed at the same time). In other words, Arch-Update could report 10 orphan packages which will actually result in 15 packages removed by pacman afterwards. As such, a "double confirmation" as a safety measure doesn't hurt.

More generally speaking, each Arch-Update run is a different case that one might want to treat differently. For instance, you could once face a situation where a package that you actually use and want to keep is reported as orphan (because you didn't install it explicitly and it is not a dependency for any package installed on your system anymore).
As such, Arch-Update is not meant to be run non-interactively (e.g. with such "confirmation skips"). 

Using such option as `--noconfirm` (which is actually discouraged in the [pacman man page](https://man.archlinux.org/man/pacman.8.en.html) itself by the way) could lead to undesirable behavior. I don't want to implement/support such an option in Arch-Update as it would most likely lead to issues like "Arch-Update broke my system [...]".
Arch-Update is designed to act as an helper rather than a decision maker.

I've shared some other thoughts and rationals about why I don't want to implement automatic actions/confirmation skips in the following issues (in case you want to read further details about this decision) :
- https://github.com/Antiz96/arch-update/issues/222
- https://github.com/Antiz96/arch-update/issues/121

Regardless, I'd like to thank you once again for your request and your overall interest in Arch-Upate! :pray:

**Comment by mehanoid** [comment]
Makes sense, thanks for the detailed reply :slightly_smiling_face:

**Comment by Tealk** [comment]
@Antiz96 Would it be possible to add an option to customize the default answer?
`Would you like to remove this orphan package (and its potential dependencies) now? [Y/n]`

**Comment by Antiz96** [comment]
> @Antiz96 Would it be possible to add an option to customize the default answer?
> `Would you like to remove this orphan package (and its potential dependencies) now? [Y/n]`
> 
> I've noticed that I rarely don't want to delete it, I'm talking about -debug packages.

Hi @Tealk 

If there are packages that you don't want to delete and therefore that shouldn't be considered as orphan, you should mark it as explicitely installed (`sudo pacman -D --asexplicit package1 package2 packageN`).

See https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Removing_unused_packages_(orphans) for more details.

**Comment by Tealk** [comment]
Sry I must have expressed myself unclear, almost always when the question comes I also want to delete the packages, there have been maybe 1-2 times since I use arch the situation that I did not want to delete the packages.

**Comment by Antiz96** [comment]
Ah sorry, I misread your message and misunderstood your demand 😅

The default answer is already "Y" (yes).  
If you mean adding an option to "autoconfirm", then no, I'm not willing to implement such "confirmation skips". 

The rationale is explained in this issue already but, to sum up, the list of packages reported as orphans by Arch-Update might slightly differ from the list of packages effectively deleted by pacman afterwards (as latter includes eventual dependencies of said orphan packages). As such, explicit confirmations from the users are a safety I'm not willing get rid of.

More generally speaking, Arch-Update is meant to act as a helper rather than a decision maker. Each updates is a different case that needs ackowledged and may need to be treated differently. Adding such "confirmation skips" may encourage people to skip reading Arch-Update output which may lead to undesired actions / package removal.

So, I'm sorry, but adding an option to automatically answer "yes" to remove orphan packages (or to any other fonctions) is not planned. 😊
