### ISSUE TITLE
Qt Arch-Update systray applet -> right click on the Arch-Update systray icon open both the app and the menu

### ISSUE THREAD

**Issue by Delor3an91** [Antiz96/arch-update#270]
### Environment

Manjaro XFCE
The Arch-Update version can be retrieved by running `arch-update --version` --> 3.2.2

- Distribution: Manjaro
- Arch-Update version: 3.2.2

### Description of the bug

Actual behavior of Arch-Update systray applet icon with Qt:

- left click : open `arch-update`
- right click : open `arch-update` and `arch-update` menu

Expected behavior of Arch-Update systray applet icon with Qt:

- left click : open `arch-update`
- right click : open `arch-update` menu

Wish You well

**Comment by Antiz96** [comment]
I've tested this on multiple environments (including XFCE) and asked a few other people to test this as well but no one was able to reproduce this issue. It just works like the expected behavior you described.

Arch-Update is ran whenever the systray icon is "activated" (using the [QSystemTrayIcon classs](https://doc.qt.io/qt-6/qsystemtrayicon.html#activated)), which means "left-clicked" by default. The menu uses the [QMenu class](https://doc.qt.io/qt-6/qmenu.html#details) which, as you can see from the linked description, is usually opened when right-clicking.

Unless I'm mistaken, this sounds more like a behavior / settings of your panel rather than an Arch-Update issue.
Assuming you're using `xfce4-panel` (since you mentioned using XFCE), there is definitely a way to make it work as the expected behavior you described since it works like that for me on my XFCE test environment (for what it's worth, I use the "default" settings for xfce4-panel, I haven't touched anything).

**Comment by SkyLLerGithub** [comment]
Sorry for necroing

Have you ever figured this out? I'm also getting this issue on my end.
I tried a new user profile and everything works as expected behavior, but i cant seem to figure out what is causing this.
I tried resetting my xfce4-panel configuration file to no avail.

**Comment by niklasschaeffer** [comment]
Yes having the same issue on xfce.

**Comment by Antiz96** [comment]
The test machine I use for Arch-Update testing is actually running XFCE and it works as expected on my side (left click runs `arch-update` & right click opens the menu).

For what it's worth my test machine is running *(vanilla)* Arch with default XFCE / xfce4-panel settings & profile. Since @SkyLLerGithub mentioned that using a new user profile works, that might come from a custom user profile shipped by your distribution maybe?

**Comment by SkyLLerGithub** [comment]
> The test machine I use for Arch-Update testing is actually running XFCE and it works as expected on my side (left click runs `arch-update` & right click opens the menu).
> 
> For what it's worth my test machine is running *(vanilla)* Arch with default XFCE / xfce4-panel settings & profile. Since @SkyLLerGithub mentioned that using a new user profile works, that might come from a custom user profile shipped by your distribution maybe?

After nuking my entire gtk.css and my entire xfcond directory everything works as normal again, i couldn't track down the cause of the issue. Unfortunately I'll just leave it at that.

**Comment by Antiz96** [comment]
For the record, someone opened a similar issue at https://github.com/Antiz96/arch-update/issues/324 and I was able to reproduce it this time!
It's still unclear what the actual root cause is, but I'm investigating. Hopefully I'll find something... 🤞 

Feel free to join the discussion on the new issue linked above, I'll keep the investigation going there ;)

**Comment by Antiz96** [comment]
Seems like I was able to find the actual cause of the issue and a workaround for it. See https://github.com/Antiz96/arch-update/issues/324#issuecomment-2676995631 🙂
