### ISSUE TITLE
How to integrate the icon (cinnamon desktop)?

### ISSUE THREAD

**Issue by daddy33** [Antiz96/arch-update#50]
Hello,

I read carefully the readme, but I don't understand exactly how you integrate the .desktop file. I tried to add the app to the cinnamon panel from the menu into the launcher applet. It works except that the icon does not change when there are updates. 
Can you please detail the steps you used on your DE to integrate a dynamic icon?

Thanks in advance.

**Comment by Antiz96** [comment]
Hi,

The way you integrated the .desktop file to the panel is correct, the issue seems to be that the cinnamon panel doesn't support a "real time" refresh of icons:

- https://forums.linuxmint.com/viewtopic.php?t=221788
- https://forums.linuxmint.com/viewtopic.php?f=211&t=343217

Unfortunately, I can't think of an easy **and** elegant solution to this right now: Making `arch-update` restart the cinnamon panel each time the icon is changed to enforce the icon update feels dirty...

Turning `arch-update` into an actual "systray" could be a potential solution but this is something I initially wanted to avoid since it would involve a complete remake of *some of* the components and would remove the freedom of integrating it anywhere you want (desktop, panel, dock, top bar...) since "systrays" only integrate in a "systray" area.
I'll still take a look at it just out of curiosity but I can't promise I'll consider it.

For now, you could either try to contact cinnamon's forum/upstream to see if supporting real time refresh of icons is a possibility and/or integrate `arch-update` somewhere else that already supports this (could be your desktop, app menu or an alternative dock/panel such as `plank` for instance).

**Comment by Antiz96** [comment]
@daddy33 Can this issue be closed or you need any more info?

**Comment by Antiz96** [comment]
Hi,

Sorry for *necro-bumping* this issue, but I just wanted to let you know (as well as everyone passing by) that Arch-Update now has a proper [systray applet](https://github.com/Antiz96/arch-update?tab=readme-ov-file#the-systray-applet) that automatically fits and runs properly in the Cinnamon systray!

After updating to Arch-Update [v2.0.0](https://github.com/Antiz96/arch-update/releases/tag/v2.0.0), you can remove the `.desktop` icon from your panel and start the systray applet instead, like so:
`systemctl --user enable --now arch-update-tray.service`
