### ISSUE TITLE
Icon too big in KDE widget bar

### ISSUE THREAD

**Issue by jfchadeyron** [Antiz96/arch-update#92]
Archlinux with KDE,
is possible too have a smaller icon ?
Thanks
 ![Screenshot_20240108_110927](https://github.com/Antiz96/arch-update/assets/78847492/3a557d5b-2d83-4f68-96dd-99d7e0e88339)

**Comment by Antiz96** [comment]
Hello,

Icons are SVGs, so they should resize automatically.
I'm not using KDE myself but I assume you put the icon in the taskbar instead of putting it in the "applet zone" on the right.

See this video: https://www.youtube.com/watch?v=8r7FfzdlnnE

Let me know how it went :)

**Comment by jfchadeyron** [comment]
Same issue like video...the icon is bigger than other.

**Comment by Antiz96** [comment]
I tried that in a VM and it's indeed because the icon is in the task bar and not the "widget" bar.
I could move it to the "widget" bar by entering the "edit mode" (right click on the task bar) and then drag and drop the icon to the right of the vertical line that separate the task bar from the widget bar. 

See the screenshots below:
![image](https://github.com/Antiz96/arch-update/assets/53110319/a2b95385-e86f-4aa1-a2c9-0ca23e0ce982)
![image](https://github.com/Antiz96/arch-update/assets/53110319/47659ee5-ce8e-4f95-b6f1-22eb6ffe2927)
![image](https://github.com/Antiz96/arch-update/assets/53110319/054a27a9-5358-4ea1-a947-8aada1ba718d)
![image](https://github.com/Antiz96/arch-update/assets/53110319/3a77f646-37df-4ce9-a282-33fc6315b30d)

That should size the icon correctly.
Let me know :)

**Comment by jfchadeyron** [comment]
![Screenshot_20240108_164939](https://github.com/Antiz96/arch-update/assets/78847492/ee22e01e-5c31-4cab-9ea5-6a23dce26174)
Sorry but arch-update is after the vertical line

**Comment by Antiz96** [comment]
Well... It's weird because I could make it work as intended on my side... 
Can you try to remove it completely from the bar, then re-add it to the widget zone and try to drag and drop it after the vertical line via the edit mode again, just in case?

Anyway, that's definitely a KDE issue, not an Arch-Update bug. :/

**Comment by Antiz96** [comment]
> ![Screenshot_20240108_164939](https://private-user-images.githubusercontent.com/78847492/294957055-ee22e01e-5c31-4cab-9ea5-6a23dce26174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzA2NzksIm5iZiI6MTcwNDczMDM3OSwicGF0aCI6Ii83ODg0NzQ5Mi8yOTQ5NTcwNTUtZWUyMmUwMWUtNWMzMS00Y2FiLTllYTUtNmEyM2RjZTI2MTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE2MTI1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNWNkMTYzMGY1OGFmZjBiY2FiYmU5NTBmMDJkZTNlYjQ0OGY0MWU2ZmQ0ZGNhMWJhZmM0MmNlZGExMzc4YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._mF3_ckBbIh7pc-B8WHRmvc4Za5YsYPl0mIg0MQQ6M8) 
Sorry but arch-update is after the vertical line

The vertical line on your screenshot seems shorter than the one on my screenshots. Is it the same one?
The vertical line I have on my side is an invisible delimiter between the task bar and the widget bar. It is only shown when I enter the edit mode.

It also doesn't seem like your screenshot is taken from the edit mode, as the widget bar isn't going "smaller" than the regular task bar (unlike on my second and third screenshots).

Though, as I said earlier, I'm not using KDE myself so forgive me if I'm wrong.

**Comment by Cardiacman13** [comment]
> Same issue like video...the icon is bigger than others (but as bigger as me).

No issue on my video. The icon is smaller than other. It's working on my side.

**Comment by Saroumane** [comment]
According to what I see, arch-update scales its icon in KDE  systray, other apps don't.
A few examples with different "height" values for the panel 

Best case scenario, panel height = 46 : 
![image](https://github.com/Antiz96/arch-update/assets/22261137/0d653fec-d63d-4d0c-a321-ba4b63fee4ff)

I use panel height = 60 :
![image](https://github.com/Antiz96/arch-update/assets/22261137/917c15f6-1c30-4b02-bed8-ac15ecfd1127)

"Worst case" : 
![image](https://github.com/Antiz96/arch-update/assets/22261137/019660ac-8fff-4257-95ae-0ee73602894b)

**Comment by Antiz96** [comment]
> According to what I see, arch-update scales its icon in KDE systray, other apps don't. A few examples with different "height" values for the panel
> 
Hi, thanks for the explanations!
That makes sense because other apps are proper systray's icons (stuck to the regular "systray size") whereas arch-update's icon is simply the SVG icon used in the [.desktop file](https://github.com/Antiz96/arch-update/blob/main/res/desktop/arch-update.desktop#L5) just like any other "regular" apps, which explains why the icon scales to the panel height instead.

So I guess the answer for that issue is either to use a panel height that scales the arch-update icon at the same size as other systray in the widget bar, meaning "46" or less according to @Saroumane's input (note that the default seems to be "44", at least on my VM, which is suitable), or to integrate the arch-update's icon somewhere else (for instance in the "task bar" on the left of the panel with the other regular apps).

**Comment by Saroumane** [comment]
@Antiz96 
Personally, I can live with a slightly bigger icon.
Btw, thanks for arch-update : it really saves a lot of time. (The last tweak I need to find is how to avoid entering the sudo password for each update. Maybe I should use the setuid bit... but I am off topic)

**Comment by Antiz96** [comment]
I guess we have all the information needed about this issue now.

Allow me to close it :)

**Comment by Antiz96** [comment]
> i found something about this : small size icon option don't work with arch-update

Once again, that's because this option is made for systray icons which arch-update is not.
The arch-update icon is like any other "regular" app icon such as the spotify, discover, settings, calculator and screenshot tool icons that you have on the left of your panel. Notice how these icons are not affected by this "small size icon option" too. The arch-update icon will have the same behavior as those ones.

As mentioned earlier, you can either reduce the height of your panel to "force" the arch-update icon to a smaller size within the systray zone or you can move the arch-update icon to left of the panel with your other applications icon (since they should have all the same size).

**Comment by Antiz96** [comment]
> Edit : I think I found a safer way than using setuid. Instead I just put these lines in `/etc/sudoers` (with `sudoedit` )
> 
> ```
> %wheel ALL=(ALL) NOPASSWD: /usr/bin/pacman
> %wheel ALL=(ALL) NOPASSWD: /usr/bin/paccache
> %wheel ALL=(ALL) NOPASSWD: /usr/bin/yay
> ```
> 
> (Assuming the user using `arch-update` is in the wheel group, and he uses yay as AUR helper.)

@Saroumane That's actually way less secure. With a `setuid`, the user has root privileges only during the execution of the script and only for what's instructed in the script. Though it's important to note that using `setuid` will break the desktop notification sent by the `--check` function and the systemd timer (as a notification sent as root won't be able to be shown on the user's graphical session as is).
With the solution you used, the user has root privileges (by being able to run sudo without requiring a password) for every `pacman`, `paccache` and `yay` operations, meaning that everyone accessing your computer would be able to install any package (even a potentially malicious one from the AUR) or remove any package from your system without any form of identity confirmation (since password is not required anymore). It may eventually be more convenient than `setuid` but definitely not more secure.

I guess the actual safest method to avoid having to input your password when running `arch-update` would be to give the ability to your user *(instead of the whole wheel group)* to run it with sudo without password, like so:

```
username ALL=(ALL) NOPASSWD: /usr/bin/arch-update
```

And then to copy the `/usr/share/applications/arch-update.desktop` file to `~/.local/share/applications/` and modify it to launch `arch-update` with sudo privileges in the "Exec" part like so:

```
[Desktop Entry]
Type=Application
Terminal=true
Name=Arch-Update
Icon=/usr/share/icons/arch-update/arch-update.svg
Exec=sudo arch-update
```

That way, your user has root privileges only during the execution of the script when clicking on the icon and only for what's specifically instructed in the script (unlike your method) and it won't break the desktop notification sent by the systemd timer either (unlike the `setuid` method).

That being said, despite giving details about the above potential solution, I feel like it is important to remind that updating the system is a regular administration task that always represents a risk and that should be done safely. Requiring a password to update your system using sudo/doas with a regular user is a common thing and is the default behavior on basically any distro there is, I don't see why it should be different when it comes to `Arch-Update`. 
All of this to say that I personally don't recommend tweaking your system and/or `arch-update` itself for the sole purpose to avoid having to type your password while doing the regular administration task that is updating your system. This is insecure and, depending on how `arch-update` components themself have been modified to achieve this, is unsupported as well (as it can lead to breakages or unexpected behavior, for instance the `setuid` breaking the desktop notification as I mentioned earlier).

That does not prevent you to do it, obviously. But keep in mind that you're doing that at your own risks and that such setup are not supported nor taken into consideration when developing, testing and bringing support regarding arch-update.

Anyhow, as you said, this off topic regarding this specific thread and I think everything is now said on that matter anyway. :smile:

**Comment by Saroumane** [comment]
It's not that simple, using setuid expose yourself to a new kind of threat : privilege escalation of setuid binaries.
Maybe you can assume your code is perfectly safe on this matter,  but I won't 😁

I have knowingly chosen my risks and I have other security measures to secure my computer.

**Comment by Antiz96** [comment]
1 - I can assure you my code is safe regarding privilege escalation as it clearly defines what operation is done/permitted with pacman, yay, etc... (unlike your solution which gives elevated privileges on the entire pacman binary allowing every operations without any filter whatsoever, even outside of the script). It's actually pretty easy to test and verify, you are free to audit my code yourself :)

2 - Unlike the solution I described, your solution actually expose you to the threat you're describing since `yay` and `pacman` themself are not safe regarding privileges escalation. Keep in mind that running a binary with sudo or with setuid is exactly the same thing in the end. So by giving elevated privileges on the whole `pacman` binary like you do with your solution, anyone can become root on your machine, because doing a privilege escalation with sudo/setuid on pacman is really easy to do. I repeat, your solution is **not** safe as is. Way less safe than the one I described, trust me. You should at least specify the operation allowed to run with sudo to restrict them to the ones needed by the script like: `%wheel ALL=(ALL) NOPASSWD: /usr/bin/pacman -Syu, /usr/bin/pacman -xxx, etc...`. But at this point, it's just better to allow `sudo` on the script itself.

3 - Regardless of the two above points, I actually made clear that I do not recommend any of the described solutions, that they are **all** insecure and not supported. `Arch-Update` is just not meant to be run this way.

Once again, this is off topic regarding this specific thread and I think I made my position on that clear enough (see point 3 above).
Let's just drop that topic please :slightly_smiling_face:

**Comment by Saroumane** [comment]
> > Requiring a password to update your system using sudo/doas with a regular user is a common thing and is the default behavior on basically any distro there is, I don't see why it should be different when it comes to `Arch-Update`. 

That is very debatable.
Regarding linux based OS :
- Ubuntu does not require it (except for kernel update), I don't know if it's the case of all its Ubuntu-based OS
- Android does not require it

And if you zoom out : 
- Windows does not require it (most of the time)
-  iOS does not require it (most of the time)

In fact it is not required for 99% of computer users on this planet. Security is handled differently.

**Comment by Antiz96** [comment]
You can disagree with me if you want, but this is objectively wrong... :sweat_smile: 

![image](https://github.com/Antiz96/arch-update/assets/53110319/6c40f39f-bc22-4436-a4ae-89073d1a5049)

As stated in the above screenshot, setuid on `/usr/bin/pacman` (which is owned by root) is exactly the same as running it with sudo in terms of privileges (and the same also regarding potential privilege escalation threats). What is the difference between using setuid to run pacman as root and running it with sudo to also run it as root? Different method but same result.

You can actually try that on your side by setting suid on `/usr/bin/whoami` and run `whoami`. Then remove the suid bit and run `sudo whoami` and just compare the results :)

By giving sudo permissions without password on the entire pacman binary like you did, you basically gave the same permissions as if you setuid on /usr/bin/pacman to the whole wheel group. And pacman itself as whole is **not** "privilege escalation" proof. Apart from the fact that anyone with an access to your session can now install/remove packages as they please, they can even become root really easily by doing a privilege escalation with pacman without having to know nor type any password.

What you described as a "safer" solution is objectively **not** secure, actually way less secure than other potential solutions presented until then. Though, if you're aware of that and you're fine with it, then there's no problem I guess! :slightly_smiling_face: 

That being said, I hope you're not taking this wrongly and I'm sorry if you did, that wasn't my intention...  
But understand that other people may not be aware of the above and can blindly apply what you showed, compromising the security of their computer in the process.

More importantly, generally speaking and regardless of all of the above, my intention as the developer/maintainer of this application is to state that **any** tweaks/solutions aiming to run `arch-update` without password represents a security concern and can lead to unexpected/undesired behavior. According to that, such setups are not supported.

I think the above statement is enough to call out this topic entirely. Anyone is obviously free to do whatever they want but should also be aware of the risks it implies (both in terms of security and `arch-update` potential breakages) and also be aware that, with that kind of setup, it's difficult if not impossible to provide proper support/help. As such, I'd like to avoid any further discussion about that topic within the `arch-update` repository itself. 

I hope you understand my point, and thanks a lot for respecting my wish (as you said in the "Edit" of your last message) :pray: While I trust you on that, I'm still locking this issue as it has gone too off topic in my opinion. If anyone has a related issue, better to just open a new one :slightly_smiling_face:

**Comment by Antiz96** [comment]
Hi,

Sorry for *necro-bumping* this issue, but I just wanted to let you know (as well as everyone passing by) that Arch-Update now has a proper systray applet that automatically fits and runs properly in the KDE systray.

After updating to Arch-Update [v2.0.0](https://github.com/Antiz96/arch-update/releases/tag/v2.0.0), you can remove the `.desktop` icon from your panel and start the systray applet instead, like so:
`systemctl --user enable --now arch-update-tray.service`
